version: '3.4'
services:
    simulation:
        image: turtlebot3_im
        network_mode: host
        command: bash -c "pkill Xvfb; rm /tmp/.X1-lock; -v="/tmp/.gazebo/:/root/.gazebo/"; Xvfb :1 -screen scrn 640x480x16 & export DISPLAY=:1.0 && roslaunch turtlebot3_gazebo turtlebot3_world.launch"
    # slam:
    #     image: turtlebot3_im
    #     network_mode: host
    #     command: bash -c "sleep 20; pkill Xvfb; rm /tmp/.X1-lock; -v="/tmp/.gazebo/:/root/.gazebo/"; Xvfb :1 -screen scrn 640x480x16 & export DISPLAY=:1.0 && roslaunch turtlebot3_slam turtlebot3_slam.launch slam_methods:=gmapping"
    #     depends_on:
    #         - simulation