version: '3.4'
services:
    simulation:
        image: robot_rest_api
        network_mode: host
        command: bash -c "pkill Xvfb; rm /tmp/.X1-lock; rm -rf /tmp/.X*; Xvfb :101 -nolisten tcp -screen scrn 640x480x16 & export DISPLAY=:101.0  && roslaunch mir_experiments sim_untidy_small_hospital_room.launch gui:=false gui_teleop:=false"
    changes:
        image: robot_rest_api
        network_mode: host
        command: bash -c "sleep 20; roslaunch mir_experiments changes_based_on_tidy_small_room_depth_camera.launch"
        depends_on:
            - simulation
    un_pause_simulation:
        image: robot_rest_api
        network_mode: host
        command: bash -c "sleep 10; rosservice call /gazebo/unpause_physics \"{}\""
        depends_on:
            - simulation
    dummy_teleop:
        image : robot_rest_api
        network_mode: host
        command: bash -c " sleep 15; rostopic pub /cmd_vel geometry_msgs/Twist \"[0.0, 0.0, 0.0]\" \"[0.0, 0.0, 0.2]\""
        depends_on:
            - simulation
            - changes
            - un_pause_simulation
    rosbridge_server:
        image : robot_rest_api
        network_mode: host
        command: bash -c "sleep 5; roslaunch rosbridge_server rosbridge_websocket.launch"
        depends_on:
            - simulation
            - changes
            - un_pause_simulation
    tf2_web_republisher:
        image : robot_rest_api
        network_mode: host
        command: bash -c "sleep 5; rosrun tf2_web_republisher tf2_web_republisher"
        depends_on:
            - simulation
            - changes
            - un_pause_simulation
            - rosbridge_server
    octomap_mapping:
        image : robot_rest_api
        network_mode: host
        command: bash -c "sleep 5; roslaunch mir_experiments octomap_mapping_depth_camera.launch"
        depends_on:
            - simulation
            - changes
            - un_pause_simulation
            - rosbridge_server
            - tf2_web_republisher
    ros_rvv:
        image : robot_rest_api
        network_mode: host
        command: bash -c "sleep 5; rosrun ros_rvv rvv.py"
        depends_on:
            - simulation
            - changes
            - un_pause_simulation
              # - rosbridge_server
              #- tf2_web_republisher
            - octomap_mapping
    amcl:
        image : robot_rest_api
        network_mode: host
        command: bash -c "sleep 10; roslaunch mir_navigation amcl.launch"
        depends_on:
            - simulation
            - changes
            - un_pause_simulation
            - rosbridge_server
            - tf2_web_republisher
            - octomap_mapping
    move_base:
        image : robot_rest_api
        network_mode: host
        command: bash -c "sleep 12; roslaunch mir_navigation start_planner.launch"
        depends_on:
            - simulation
            - changes
            - un_pause_simulation
            - rosbridge_server
            - tf2_web_republisher
            - octomap_mapping
            - amcl
    mission_manager:
        image : robot_rest_api
        network_mode: host
        command: bash -c "python /opt/catkin_ws/src/robot_rest_api/ros/mission_manager.py"
        depends_on:
            - simulation

