version: '3.4'
services:
    simulation:
        image: example_im
        network_mode: host
        command: bash -c "pkill Xvfb; rm /tmp/.X1-lock; Xvfb :1 -screen scrn 640x480x16 & export DISPLAY=:1.0 && roslaunch kymco_maxxer90_gazebo kymco_maxxer90_empty_world.launch"
    un_pause_simulation:
        image: example_im
        network_mode: host
        command: bash -c "sleep 10; rosservice call /gazebo/unpause_physics \"{}\""
        depends_on:
            - simulation
    localization:
        image: example_im
        network_mode: host
        command: bash -c "sleep 10; roslaunch kymco_maxxer90_navigation robot_localization.launch"
        depends_on:
            - simulation
            - un_pause_simulation          
    move_base:
        image: example_im
        network_mode: host
        command: bash -c "sleep 10; roslaunch kymco_maxxer90_navigation move_base.launch"
        depends_on:
            - simulation
            - localization
            - un_pause_simulation
    octomap_mapping:
        image: example_im
        network_mode: host
        command: bash -c "sleep 10; roslaunch kymco_maxxer90_navigation octomap_mapping_depth.launch"
        depends_on:
            - simulation
            - localization
            - move_base